//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_code_frest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Productid { get; set; }
        public string ProductName { get; set; }
        public string productPrise { get; set; }
        public byte[] productImaige { get; set; }
    }
}
