// <auto-generated />
namespace Test_code_frest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class saxs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(saxs));
        
        string IMigrationMetadata.Id
        {
            get { return "201912301636213_saxs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
