// <auto-generated />
namespace Test_code_frest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class requrd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(requrd));
        
        string IMigrationMetadata.Id
        {
            get { return "201912271927110_requrd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
